### ISSUE TITLE
Will/~hadrud-lodsef is still listed on site

### ISSUE THREAD

**Issue by urcades** [urbit/tlon.io#9]
RIP Will, but he should probably be removed from the current roster.

I actually had a related question after trying to do this myself via a PR — how is this site built? I see that Will isn't located in index.hoon, but he's still contained in `dist/index.html` — if I can learn what's going on here, I can fix this issue myself.

**Comment by Fang-** [comment]
Closing as fixed by #7. See there for how the change was made. tldr: `/static-site/index.hoon`

**Comment by matildepark** [comment]
@Fang- but the question was regarding how he's *still on the live site*, after the PR was made, not about having to do the task itself.

**Comment by Fang-** [comment]
Oh, I misread, sorry.

I think we used to do bespoke `dist` generation on an urbit? Not sure what exactly the procedure for that is, @msutherl might know more.

**Comment by matildepark** [comment]
@msutherl [mentioned here](https://github.com/urbit/tlon.io/pull/8#issuecomment-517452392) that @galenwp is behind deployment -- so I imagine it's pulling from this repo onto a Unix-mounted pier of a secret Tlon flagship...?

**Comment by flowerornament** [comment]
@matildepark stealth ships
